services:
  plantuml-server:
    image: plantuml/plantuml-server:jetty
    ports:
      - 8080:8080
    env_file:
      - stack.env
    restart: always
    networks:
      - plantuml_net
networks:
  plantuml_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.10.0/29
          gateway: 172.19.10.1
    
